Add repository initialization
CntoDev/CNTOSync pull request #4
Opened 2018-04-04 05:48 UTC by enricoghdn

2018-04-05 20:06 UTC, lastmikoi requested changes
Some comments on refactors and test implementations, apart from that the feature looks sanely implemented !

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/configuration.py
> +class Configuration(object):
Can be refactored not to use a class, using module global variables. If this is a placeholder for a future dynamic configuration module then let's take the technical debt hit but let's try to avoid making complex prototypes.

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/file_sync.py
> +    if os.path.isdir(abs_directory) and os.path.isdir(index_subdirectory) and os.path.isfile(
Rather than chain ifs, one could use this idiom:
```
return all([
    os.path.isdir(abs_directory),
    os.path.isdir(index_subdirectory),
    os.path.isfile(index_file_path),
])
```

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/file_sync.py
> +    if os.path.isdir(abs_directory) and os.path.isdir(index_subdirectory) and os.path.isfile(
Supports symlinks, which is cool. :+1:

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/file_sync.py
> +                          display_name: str, uri: str, overwrite: bool = False) -> Repository:
Why not put that as a classmethod of `Repository` ?

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/file_sync.py
> +def is_repository(directory: str, configuration: configuration.Configuration) -> bool:
Since we're creating a class for `Repository`, might as well put everything in its namespace. a `check_presence` classmethod would do the trick.

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_configuration.py
> +def test_configuration():
There is no code to test in the unit, which lead to implementing a unit test that tests the python language rather than the unit.

Not having anything else to test than a class' `__init__` attribute setting is a hint as to refactor a class into a set of module variables.

2018-04-05 20:06 UTC, lastmikoi commented on cntosync/configuration.py
> +# --------------------------------License Notice----------------------------------
I see you're using the contents of `license_header.in`, which is nice. As soon as I get around releasing my `pyauthorship` tool you'll hopefully not have to do that manually ;)

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +def config(mocker):
This fixture would still be needed even after the suggested configuration class refactor.

However, assuming the module has sane defaults, I don't see the point of mocking those variables except when it comes to test-specific data (i.e. absolute paths)

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +    (((True, True), True), True),
Nested tuples are a tad hard to read, I would recommend against shoving "everything" in a variable and doing expansion later.

However, the problem would disappear if we created the directory (tmpdir) rather than mock most if not all filesystem operations. I'd rather for a test fixture to be more resistant to refactors. It would stop being a pure unit test however, which is fine when it comes to interacting with a file tree we can easily generate.

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +    mocker.patch('builtins.open')
If you repeat set-up and tear-down code a lot in tests, it's most likely to be worth having a fixture for it.

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +    dir = '/test'  # noqa: A001
Overriding builtins is a **bad** thing, as such `A001` should certainly not be suppressed.

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +def test_init_repo_return_value(config, mocker):
Mypy should check that already (that a function is indeed returning an instance of the annotated return type), as such this test *should* be redundant.

2018-04-05 20:06 UTC, lastmikoi commented on tests/test_file_sync.py
> +def test_init_repo_overwrite(overwrite, config, mocker):
Sounds like a decent approximation for the time being :+1:

2018-04-06 13:10 UTC, enricoghdn commented on cntosync/configuration.py
> +class Configuration(object):
The idea behind this empty class is to change as little code as possible once the feature will actually be implemented. The idea on `configuration` module is indeed a class to wrap the available settings and to provide methods to fetch/update/keep updated the system configuration. Specifically, a class allows properties that don't necessarily need to be declared as variables and is hence highly scalable.
This is the idea, if you think a class is unnecessary I see no problems in removing it.

2018-04-06 13:11 UTC, enricoghdn commented on cntosync/file_sync.py
> +    if os.path.isdir(abs_directory) and os.path.isdir(index_subdirectory) and os.path.isfile(
Wasn't aware of the `all()` function. Is it explicit enough for a condition statement?

2018-04-06 13:12 UTC, enrico-ghidoni commented on cntosync/file_sync.py
> +                          display_name: str, uri: str, overwrite: bool = False) -> Repository:
Because it would be a static method of such class since its ultimate purpose is to return a `Repository` class instance.

2018-04-06 13:13 UTC, enricoghdn commented on cntosync/file_sync.py
> +def is_repository(directory: str, configuration: configuration.Configuration) -> bool:
Same as above, it would be a static method of the class. Isn't it a bit too java-ish?

2018-04-06 13:15 UTC, enricoghdn commented on tests/test_configuration.py
> +def test_configuration():
As extensively explained above the idea is to have a sketch for future API of such class. Indeed there is no point in testing its `__init__` method, the test method is there for coverage purposes. Do you figure we can skip the class altogether or remove it entirely and have a major change in the `file_sync` module in the future to include the new configuration API?

2018-04-06 13:16 UTC, enricoghdn commented on cntosync/configuration.py
> +# --------------------------------License Notice----------------------------------
I tried to setup my IDE to put it in every `.py` file I create but it's just faster to do it manually.

2018-04-06 13:21 UTC, enrico-ghidoni commented on tests/test_file_sync.py
> +def config(mocker):
Right, the original idea was to have a strict control over paths generated and then used by the unit under testing. In the end dynamic validation is used anyways so I'll keep the `config` fixture but return an actual `configuration.Configuration` object.

2018-04-06 13:25 UTC, enricoghdn commented on tests/test_file_sync.py
> +    (((True, True), True), True),
We decided to strictly stick to unit testing instead of behavioural testing. It is in the plans to make a custom module that deals with temporary directory but it's not a feature I would include in unit testing as mocking almost every filesystem call works fine and allows the required tests to be executed.

2018-04-06 13:25 UTC, enricoghdn commented on tests/test_file_sync.py
> +    mocker.patch('builtins.open')
Will move into one!

2018-04-06 13:25 UTC, enricoghdn commented on tests/test_file_sync.py
> +    dir = '/test'  # noqa: A001
Damn it, was so proud of muting flake8 on it.

2018-04-06 13:28 UTC, enricoghdn commented on tests/test_file_sync.py
> +def test_init_repo_return_value(config, mocker):
It is redundant, `mypy` works. Yay. Will remove.

2018-04-06 13:29 UTC, enricoghdn commented on tests/test_file_sync.py
> +def test_init_repo_overwrite(overwrite, config, mocker):
Why only "decent"?

2018-04-08 12:42 UTC, lastmikoi commented on cntosync/configuration.py
> +class Configuration(object):
For the time being we don't need a class. Thus putting a class (and doing meaningless tests about it because we don't actually make use of it) is generating technical debt. That's a mild case of overengineering. We'll use a class when we'll need it: we need to make sure the code is tolerant to changes anyway.

2018-04-08 12:45 UTC, lastmikoi commented on cntosync/file_sync.py
> +def is_repository(directory: str, configuration: configuration.Configuration) -> bool:
It's object oriented programming. What would be too java-ish would be to put everything in classes and disregarding the usefulness of flat functions.

Here this function is very much related to the implementation of the `Repository` generation, which is a class.

2018-04-08 12:50 UTC, lastmikoi commented on cntosync/file_sync.py
> +    if os.path.isdir(abs_directory) and os.path.isdir(index_subdirectory) and os.path.isfile(
For a condition, no. For a return value yes, which is the case here.

For the case where you are forced to have complex condition statements, I've been using that:

```
if cond_1\
   and cond_2\
   and cond_3:
    pass
```

2018-04-08 12:53 UTC, lastmikoi commented on cntosync/file_sync.py
> +                          display_name: str, uri: str, overwrite: bool = False) -> Repository:
Which is totally fine. `Repository.__new__` is a already static method that returns a new instance of `Repository` of which the instance's `__init__` has been called (https://docs.python.org/3.6/reference/datamodel.html#object.__new__). As such there's no issue with you having a static method that has a similar behaviour. Avoid overriding `__new__` though.

2018-04-08 12:55 UTC, lastmikoi commented on tests/test_configuration.py
> +def test_configuration():
CNTOSync is in heavy development stage, if there's a moment where we can afford to do major changes it's now.

We won't do a release without the configuration feature anyway, so putting a placeholder (even if not forward-compatible with the final implementation) is completely fine.

2018-04-08 12:57 UTC, lastmikoi commented on tests/test_file_sync.py
> +    (((True, True), True), True),
It would still be unit testing.

Do you test that your unit calls `os.path.isdir` or do you test that your unit (`is_repository`) is able to detect if a given directory is a repository ?

There is no definition of feature, scenarios, gherkin syntax or anything of the like that would imply behavioural testing.

2018-04-08 13:03 UTC, lastmikoi commented on tests/test_file_sync.py
> +def test_init_repo_overwrite(overwrite, config, mocker):
Because the action of "overwriting" a given repository isn't actually tied to calling `mkdir` on it. [mkdir(3P)](http://man7.org/linux/man-pages/man3/mkdir.3p.html) isn't a destructive system call.

We should rather look is the file has been written to.

2018-04-09 15:27 UTC, enricoghdn commented on tests/test_file_sync.py
> +def config(mocker):
Change of plans: will remove `config` fixture since `configuration.Configuration` class will be removed as well. Instead I will simply import the `configuration` module.

2018-04-09 15:28 UTC, enricoghdn commented on tests/test_file_sync.py
> +    (((True, True), True), True),
This needs further development of a standalone directory-faking module, as described in https://trello.com/c/h3AV8WiR

2018-04-10 05:33 UTC, enricoghdn commented
A couple of issues are still to resolve, don’t close yet.

2018-04-10 07:32 UTC, enricoghdn commented
Issues that need to be worked out:
- introduce fixture for redundant mocks. Fixture should offer access to the mocked objects to make assertions on calls
- usage of temporary directory for tests, see https://trello.com/c/h3AV8WiR

2018-04-10 15:29 UTC, enricoghdn commented
@lastmikoi all changes discussed are fixed with the exception of reworking tests to make use of a directory fixture. Task is listed in Trello.

2018-04-14 14:27 UTC, lastmikoi requested changes
A small change on the usage of `cls` in class methods and an optional suggestion on exception handling.

2018-04-14 14:27 UTC, lastmikoi commented on cntosync/file_sync.py
> +        if Repository.check_presence(directory) and not overwrite:
Use `cls` instead of a direct reference to `Repository`. It's the same but if we are to subclass `Repository` then that subclass' `initialize` would call the subclass' `check_presence` rather than a hard to debug behaviour.

2018-04-14 14:27 UTC, lastmikoi commented on tests/test_file_sync.py
> +    uri = 'file://something'
I like dem URLs :+1:

2018-04-14 14:27 UTC, lastmikoi commented on tests/test_file_sync.py
> +    with pytest.raises(ValueError):
Optional: Create an exception that subclasses `ValueError` but has a more specific message and name to reflect the unsupported schema.

`requests` does such a thing: https://github.com/requests/requests/blob/master/requests/exceptions.py#L80

2018-04-15 12:19 UTC, enrico-ghidoni commented on tests/test_file_sync.py
> +    uri = 'file://something'
Is that a go or what?

2018-04-15 12:19 UTC, enrico-ghidoni commented on cntosync/file_sync.py
> +        if Repository.check_presence(directory) and not overwrite:
Will fix! Good catch

2018-04-15 12:19 UTC, enrico-ghidoni commented on tests/test_file_sync.py
> +    with pytest.raises(ValueError):
Sounds good, will do

2018-04-19 10:50 UTC, enricoghdn commented
Seems like `pytest-mypy==0.3.1` isn't a great fan of `mypy==0.560`. This is solved in #6 .

2018-04-21 18:01 UTC, lastmikoi commented
@enricoghdn Ah! Apparently the "Update branch" button merges develop into the PR branch.

This should serve as an early idea of the travis run but I'd welcome it if you could rebase your PR against develop.

2018-04-21 18:05 UTC, lastmikoi submitted a review, later dismissed

2018-04-23 07:51 UTC, enricoghdn commented
This should be ready for merging.

2018-04-24 06:43 UTC, lastmikoi approved these changes

2018-04-24 06:43 UTC, merged